### ISSUE TITLE
Violation of Terms of Service

### ISSUE THREAD

**Issue by toddy86** [woblers/rightmove_webscraper.py#14]
Hi, 

I just wanted to make everyone aware that the use of a web scraper on the rightmove.co.uk website is now against their terms of service. 

It previously was allowed and I too had assumed it was still allowed. However, if you read the later comments on the below stackoverflow thread (don't just read the accepted solution) and read their ToS, they now explicitly ban the use of any and all web scrapers. 

https://stackoverflow.com/questions/36662524/rightmove-api-and-scraping-technical-and-legal
https://www.rightmove.co.uk/this-site/terms-of-use.html

Just a heads up to anyone who might be wanting to use this library. 

Todd

**Comment by woblers** [comment]
Hey thanks for letting us know. I don't particularly regard this as an issue as I don't think this is enforceable but is probably worth knowing if people are using this in a work context, so I will add a note to the readme.
