### ISSUE TITLE
Not a full list

### ISSUE THREAD

**Issue by cyberience** [woblers/rightmove_webscraper.py#16]
This is a nice program and was testing it out, I notice that only the first 29 rows and then the last 29 rows are returned when doing a .get_results,
Is this an issue, or is it something done by right move?

**Comment by woblers** [comment]
Hey, could you provide an example of the search you ran when you found this problem?

**Comment by cyberience** [comment]
"https://www.rightmove.co.uk/property-for-sale/find.html?searchType=SALE&locationIdentifier=REGION%5E904"

**Comment by woblers** [comment]
Ok I tested that URL and it worked correctly - pulled in over 1000+ results. I think the issue you are referring to is that when you inspect a Pandas DataFrame in a Jupyter Notebook, it truncates the number of rows it displays and only shows the first 29 and last 29.

If you want to display other rows in the notebook you can index them, e.g.

`df.loc[50:100, :]`

Or you can dump the whole DataFrame to CSV to use in another program, e.g.

`df.to_csv("./path/to/filename.csv",  encoding="utf-8", index=False)`

There are hundreds of methods for analysing and interrogating data in Pandas! Jupyter is just an IDE for coding in Python which is used for convenience in this repository to demonstrate the usage of the webscraper.

Hope this helps.
