### ISSUE TITLE
Floating point page count

### ISSUE THREAD

**Issue by Uplink03** [woblers/rightmove_webscraper.py#7]
In Python 3 `result_pages_count` returns a floating point number and that makes `get_results` explode at line 103. In Python 2 it's fine because both the division operands are integers.

I suggest the following diff, using explicit floor division. This fixes Python 3 and also works in Python 2.

```diff
diff --git a/rightmove_webscraper.py b/rightmove_webscraper.py
index aabb56e..837b582 100644
--- a/rightmove_webscraper.py
+++ b/rightmove_webscraper.py
@@ -37,7 +37,7 @@ class rightmove_data(object):
         There are 24 results on each results page, but note that the
         rightmove website limits results pages to a maximum of 42 pages."""
 
-        page_count = self.results_count() / 24
+        page_count = self.results_count() // 24
         if self.results_count() % 24 > 0:
             page_count += 1
 
```

**Comment by woblers** [comment]
Thanks for this -  I wrote this in Python 2 and hadn't actually tested in 3, much appreciated.

**Comment by Uplink03** [comment]
I usually use Python 2 too, but I installed Jupyter Notebook with Python 3 following their instructions (I never used it before) and hit this bug with a page count of 2.78 or similar :)
